--------------------------------------------------------
--  File created - Salý-Ocak-11-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CALISANLAR
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CALISANLAR" 
   (	"CALISAN_NO" NUMBER(4,0), 
	"ISIM" VARCHAR2(12 BYTE), 
	"SOYISIM" VARCHAR2(12 BYTE), 
	"DOGUM_TARIHI" VARCHAR2(10 BYTE), 
	"DOGUM_YERI" VARCHAR2(12 BYTE), 
	"ADRES" VARCHAR2(60 BYTE), 
	"TELEFON" VARCHAR2(12 BYTE), 
	"CINSIYET" VARCHAR2(5 BYTE), 
	"GOREV" VARCHAR2(30 BYTE), 
	"SIGORTA_NO" VARCHAR2(12 BYTE), 
	"BANKA_HESAP_NO" VARCHAR2(12 BYTE), 
	"MAAS" NUMBER(4,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.CALISANLAR
SET DEFINE OFF;
Insert into SYSTEM.CALISANLAR (CALISAN_NO,ISIM,SOYISIM,DOGUM_TARIHI,DOGUM_YERI,ADRES,TELEFON,CINSIYET,GOREV,SIGORTA_NO,BANKA_HESAP_NO,MAAS) values ('1000','Mustafa','Karataþ','10/02/1973','Sivas','Esenevler,20, 80010, Merkez/Istanbul, Turkey','05475211245','E','Müdür','141511','TR1000594723','7500');
Insert into SYSTEM.CALISANLAR (CALISAN_NO,ISIM,SOYISIM,DOGUM_TARIHI,DOGUM_YERI,ADRES,TELEFON,CINSIYET,GOREV,SIGORTA_NO,BANKA_HESAP_NO,MAAS) values ('1002','Hasan','Özaslan','21/03/1977','Ýstanbul','Daðseven,24, 65900, Gürpinar/Istanbul, Turkey','05519896951','E','Müdür yardýmcýsý','181689','TR1004554326','6750');
Insert into SYSTEM.CALISANLAR (CALISAN_NO,ISIM,SOYISIM,DOGUM_TARIHI,DOGUM_YERI,ADRES,TELEFON,CINSIYET,GOREV,SIGORTA_NO,BANKA_HESAP_NO,MAAS) values ('1003','Rukiye','Kireççi','01/06/1974','Ankara','Konak,5, 58602, Suþehri/Istanbul, Turkey','05481452554','K','Müdür yardýmcýsý','131764','TR1201989653','6750');
Insert into SYSTEM.CALISANLAR (CALISAN_NO,ISIM,SOYISIM,DOGUM_TARIHI,DOGUM_YERI,ADRES,TELEFON,CINSIYET,GOREV,SIGORTA_NO,BANKA_HESAP_NO,MAAS) values ('2356','Hacý Halil','Günaydýn','30/12/1988','Ýstanbul','Kilis,23, 49250, Merkez/Istanbul, Turkey','05694746585','E','Kasiyer','102554','TR1663110215','5000');
Insert into SYSTEM.CALISANLAR (CALISAN_NO,ISIM,SOYISIM,DOGUM_TARIHI,DOGUM_YERI,ADRES,TELEFON,CINSIYET,GOREV,SIGORTA_NO,BANKA_HESAP_NO,MAAS) values ('2774','Fatma Betül','Demirezen','15/04/1979','Kocaeli','Tosmurlu,10, 33940, Silifke/Istanbul, Turkey','05534788789','K','Kasiyer','174585','TR1780380764','4700');
Insert into SYSTEM.CALISANLAR (CALISAN_NO,ISIM,SOYISIM,DOGUM_TARIHI,DOGUM_YERI,ADRES,TELEFON,CINSIYET,GOREV,SIGORTA_NO,BANKA_HESAP_NO,MAAS) values ('3522','Vahide','Çilek','16/01/1989','Sakarya','Yukarikonak,20, 47700, Mazidaði/Istanbul, Turkey','05303778300','K','Reyon sorumlusu','255448','TR1911661041','4500');
Insert into SYSTEM.CALISANLAR (CALISAN_NO,ISIM,SOYISIM,DOGUM_TARIHI,DOGUM_YERI,ADRES,TELEFON,CINSIYET,GOREV,SIGORTA_NO,BANKA_HESAP_NO,MAAS) values ('4861','Abdulsamet','Koç','11/11/1974','Karabük','Söðüt Köyü,17, 15902, Çavdir/Istanbul, Turkey','05231213426','E','Kasiyer','830548','TR0115548133','4850');
Insert into SYSTEM.CALISANLAR (CALISAN_NO,ISIM,SOYISIM,DOGUM_TARIHI,DOGUM_YERI,ADRES,TELEFON,CINSIYET,GOREV,SIGORTA_NO,BANKA_HESAP_NO,MAAS) values ('2955','Mahmut Arda','Turgut','05/12/1993','Ýstanbul','Gazi Mustafa Kemal,11, 35660, Menemen/Istanbul, Turkey','05396018722','E','Reyon sorumlusu','827936','TR1035454182','4000');
Insert into SYSTEM.CALISANLAR (CALISAN_NO,ISIM,SOYISIM,DOGUM_TARIHI,DOGUM_YERI,ADRES,TELEFON,CINSIYET,GOREV,SIGORTA_NO,BANKA_HESAP_NO,MAAS) values ('5174','Seçil','Tunçkol','23/05/1986','Ýstanbul','Sütlüce,1, 26555, Tepebaþi/Istanbul, Turkey','05295010171','K','Reyon sorumlusu','531641','TR1998475152','4400');
Insert into SYSTEM.CALISANLAR (CALISAN_NO,ISIM,SOYISIM,DOGUM_TARIHI,DOGUM_YERI,ADRES,TELEFON,CINSIYET,GOREV,SIGORTA_NO,BANKA_HESAP_NO,MAAS) values ('2729','Nihal','Satan','18/09/1996','Tekirdað','Eþrefzade,15, 16860, Ýznik/Istanbul, Turkey','05842951579','K','Reyon sorumlusu','284959','TR1893020424','4100');
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TABLE1_PK" ON "SYSTEM"."CALISANLAR" ("CALISAN_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger TRG_GIRIS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."TRG_GIRIS" 
AFTER INSERT
ON CALISANLAR
FOR EACH ROW
BEGIN
INSERT INTO GIRIS(CALISAN_NO, GOREV, SIFRE) VALUES (:NEW.CALISAN_NO,:NEW.GOREV,NULL);
end;
/
ALTER TRIGGER "SYSTEM"."TRG_GIRIS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_SILME
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."TRG_SILME" 
AFTER DELETE
ON CALISANLAR
FOR EACH ROW
BEGIN
DELETE FROM GIRIS WHERE CALISAN_NO=:OLD.CALISAN_NO;
end;
/
ALTER TRIGGER "SYSTEM"."TRG_SILME" ENABLE;
--------------------------------------------------------
--  Constraints for Table CALISANLAR
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CALISANLAR" MODIFY ("CALISAN_NO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CALISANLAR" MODIFY ("ISIM" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CALISANLAR" MODIFY ("SOYISIM" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CALISANLAR" MODIFY ("DOGUM_TARIHI" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CALISANLAR" MODIFY ("DOGUM_YERI" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CALISANLAR" MODIFY ("ADRES" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CALISANLAR" MODIFY ("TELEFON" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CALISANLAR" MODIFY ("CINSIYET" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CALISANLAR" MODIFY ("GOREV" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CALISANLAR" MODIFY ("SIGORTA_NO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CALISANLAR" MODIFY ("BANKA_HESAP_NO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CALISANLAR" MODIFY ("MAAS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CALISANLAR" ADD CONSTRAINT "CALISANLAR_PK" PRIMARY KEY ("CALISAN_NO")
  USING INDEX (CREATE UNIQUE INDEX "SYSTEM"."TABLE1_PK" ON "SYSTEM"."CALISANLAR" ("CALISAN_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" )  ENABLE;
