--------------------------------------------------------
--  File created - Salý-Ocak-11-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SATISLAR
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."SATISLAR" 
   (	"SATIS_NO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"URUN_NO" NUMBER(5,0), 
	"CALISAN_NO" NUMBER(4,0), 
	"MUSTERI_CARD_NO" VARCHAR2(12 BYTE), 
	"SATIS_TARIHI" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.SATISLAR
SET DEFINE OFF;
Insert into SYSTEM.SATISLAR (SATIS_NO,URUN_NO,CALISAN_NO,MUSTERI_CARD_NO,SATIS_TARIHI) values ('1','51655','2356','L7773',to_date('12/10/2021','DD/MM/RRRR'));
Insert into SYSTEM.SATISLAR (SATIS_NO,URUN_NO,CALISAN_NO,MUSTERI_CARD_NO,SATIS_TARIHI) values ('2','51655','2356','L7773',to_date('10/12/2021','DD/MM/RRRR'));
Insert into SYSTEM.SATISLAR (SATIS_NO,URUN_NO,CALISAN_NO,MUSTERI_CARD_NO,SATIS_TARIHI) values ('3','70587','2356','L7773',to_date('02/01/2022','DD/MM/RRRR'));
Insert into SYSTEM.SATISLAR (SATIS_NO,URUN_NO,CALISAN_NO,MUSTERI_CARD_NO,SATIS_TARIHI) values ('4','88670','2774','B5334',to_date('02/01/2022','DD/MM/RRRR'));
Insert into SYSTEM.SATISLAR (SATIS_NO,URUN_NO,CALISAN_NO,MUSTERI_CARD_NO,SATIS_TARIHI) values ('21','35153','2774','B5121',to_date('06/01/2022','DD/MM/RRRR'));
Insert into SYSTEM.SATISLAR (SATIS_NO,URUN_NO,CALISAN_NO,MUSTERI_CARD_NO,SATIS_TARIHI) values ('22','68456','2356','B5121',to_date('06/01/2022','DD/MM/RRRR'));
Insert into SYSTEM.SATISLAR (SATIS_NO,URUN_NO,CALISAN_NO,MUSTERI_CARD_NO,SATIS_TARIHI) values ('41','30051','4861','T5209',to_date('07/01/2022','DD/MM/RRRR'));
Insert into SYSTEM.SATISLAR (SATIS_NO,URUN_NO,CALISAN_NO,MUSTERI_CARD_NO,SATIS_TARIHI) values ('42','31111','4861','T5209',to_date('07/01/2022','DD/MM/RRRR'));
Insert into SYSTEM.SATISLAR (SATIS_NO,URUN_NO,CALISAN_NO,MUSTERI_CARD_NO,SATIS_TARIHI) values ('43','74917','2356','B5334',to_date('07/01/2022','DD/MM/RRRR'));
Insert into SYSTEM.SATISLAR (SATIS_NO,URUN_NO,CALISAN_NO,MUSTERI_CARD_NO,SATIS_TARIHI) values ('61','30051','2356','T5209',to_date('10/01/2022','DD/MM/RRRR'));
--------------------------------------------------------
--  DDL for Index SATISLAR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SATISLAR_PK" ON "SYSTEM"."SATISLAR" ("SATIS_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger TRG_SATIS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."TRG_SATIS" 
AFTER INSERT
ON SATISLAR
FOR EACH ROW
BEGIN
UPDATE STOKLAR SET URUN_SAYISI = (URUN_SAYISI-1) 
WHERE URUN_NO=:NEW.URUN_NO;
END;
/
ALTER TRIGGER "SYSTEM"."TRG_SATIS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PUAN
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."TRG_PUAN" 
AFTER INSERT
ON SATISLAR
FOR EACH ROW
BEGIN
UPDATE MUSTERILER SET TOPLAM_PUAN = (TOPLAM_PUAN+1) 
WHERE MUSTERI_CARD_NO=:NEW.MUSTERI_CARD_NO;
end;
/
ALTER TRIGGER "SYSTEM"."TRG_PUAN" ENABLE;
--------------------------------------------------------
--  Constraints for Table SATISLAR
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."SATISLAR" MODIFY ("SATIS_NO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SATISLAR" ADD CONSTRAINT "SATISLAR_PK" PRIMARY KEY ("SATIS_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."SATISLAR" MODIFY ("URUN_NO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SATISLAR" MODIFY ("CALISAN_NO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SATISLAR" MODIFY ("MUSTERI_CARD_NO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SATISLAR" MODIFY ("SATIS_TARIHI" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SATISLAR
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."SATISLAR" ADD FOREIGN KEY ("URUN_NO")
	  REFERENCES "SYSTEM"."URUNLER" ("URUN_NO") ENABLE;
  ALTER TABLE "SYSTEM"."SATISLAR" ADD FOREIGN KEY ("CALISAN_NO")
	  REFERENCES "SYSTEM"."CALISANLAR" ("CALISAN_NO") ENABLE;
  ALTER TABLE "SYSTEM"."SATISLAR" ADD FOREIGN KEY ("MUSTERI_CARD_NO")
	  REFERENCES "SYSTEM"."MUSTERILER" ("MUSTERI_CARD_NO") ENABLE;
