--------------------------------------------------------
--  File created - Salý-Ocak-11-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TEDARIKCILER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TEDARIKCILER" 
   (	"TEDARIKCI_NO" NUMBER(5,0), 
	"FIRMA_ISMI" VARCHAR2(35 BYTE), 
	"ADRES" VARCHAR2(65 BYTE), 
	"TELEFON" VARCHAR2(12 BYTE), 
	"E_MAÝL" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.TEDARIKCILER
SET DEFINE OFF;
Insert into SYSTEM.TEDARIKCILER (TEDARIKCI_NO,FIRMA_ISMI,ADRES,TELEFON,"E_MAÝL") values ('89156','Fermente','Hudut,8, 44500, Doðanþehir/Antalya, Turkey','03726025383','hachi@hotmail.com');
Insert into SYSTEM.TEDARIKCILER (TEDARIKCI_NO,FIRMA_ISMI,ADRES,TELEFON,"E_MAÝL") values ('65890','Anket','Somak,24, 20600, Çivril/Bursa, Turkey','03362747922','carreras@yahoo.ca');
Insert into SYSTEM.TEDARIKCILER (TEDARIKCI_NO,FIRMA_ISMI,ADRES,TELEFON,"E_MAÝL") values ('78553','Naturel','Merkez Çayircik,13, 67002, Merkez/Istanbul, Turkey','03963597533','jgoerzen@gmail.com');
Insert into SYSTEM.TEDARIKCILER (TEDARIKCI_NO,FIRMA_ISMI,ADRES,TELEFON,"E_MAÝL") values ('97509','Gýdager','Akkise,5, 42390, Ahirli/Kutahya, Turkey','03508757890','kidehen@outlook.com');
Insert into SYSTEM.TEDARIKCILER (TEDARIKCI_NO,FIRMA_ISMI,ADRES,TELEFON,"E_MAÝL") values ('56337','Raven','Dallica Köyü,34, 24602, Kemaliye/Kutahya, Turkey','03346329042','gavollink@yahoo.com');
Insert into SYSTEM.TEDARIKCILER (TEDARIKCI_NO,FIRMA_ISMI,ADRES,TELEFON,"E_MAÝL") values ('42763','Kuzey','Toprakli,6, 1900, Karataþ/Babaeski, Turkey','05417533144','yruan@yahoo.com');
Insert into SYSTEM.TEDARIKCILER (TEDARIKCI_NO,FIRMA_ISMI,ADRES,TELEFON,"E_MAÝL") values ('23586','Neus','Yukaribahçeler,4, 52400, Fatsa/Isparta, Turkey','05368755407','lamky@yahoo.com');
Insert into SYSTEM.TEDARIKCILER (TEDARIKCI_NO,FIRMA_ISMI,ADRES,TELEFON,"E_MAÝL") values ('33265','Topmar','Eþmebaþi Köyü,33, 58502, Yildizeli/Istanbul, Turkey','05729631320','danneng@gmail.com');
Insert into SYSTEM.TEDARIKCILER (TEDARIKCI_NO,FIRMA_ISMI,ADRES,TELEFON,"E_MAÝL") values ('56220','Çýnar','Hanönü,6, 32902, Gelendost/Istanbul, Turkey','03713258538','barjam@yahoo.com');
Insert into SYSTEM.TEDARIKCILER (TEDARIKCI_NO,FIRMA_ISMI,ADRES,TELEFON,"E_MAÝL") values ('35698','Güreller','Kadiköy,30, 6920, Nallihan/Istanbul, Turkey','03748340598','pedwards@hotmail.com');
--------------------------------------------------------
--  DDL for Index TEDARIKCILER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TEDARIKCILER_PK" ON "SYSTEM"."TEDARIKCILER" ("TEDARIKCI_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TEDARIKCILER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TEDARIKCILER" MODIFY ("TEDARIKCI_NO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TEDARIKCILER" MODIFY ("FIRMA_ISMI" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TEDARIKCILER" MODIFY ("ADRES" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TEDARIKCILER" MODIFY ("TELEFON" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TEDARIKCILER" MODIFY ("E_MAÝL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TEDARIKCILER" ADD CONSTRAINT "TEDARIKCILER_PK" PRIMARY KEY ("TEDARIKCI_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
