--------------------------------------------------------
--  File created - Salý-Ocak-11-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table URUN_GRUPLARI
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."URUN_GRUPLARI" 
   (	"GRUP_NO" NUMBER(3,0), 
	"URUN_GRUP_ISIM" VARCHAR2(30 BYTE), 
	"SAKLAMA_KRITERI" VARCHAR2(50 BYTE), 
	"TASIMA_KRITERI" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.URUN_GRUPLARI
SET DEFINE OFF;
Insert into SYSTEM.URUN_GRUPLARI (GRUP_NO,URUN_GRUP_ISIM,SAKLAMA_KRITERI,TASIMA_KRITERI) values ('239','Gýda-yemek ürünleri','Rafta, oda sýcaklýðýnda','Koli');
Insert into SYSTEM.URUN_GRUPLARI (GRUP_NO,URUN_GRUP_ISIM,SAKLAMA_KRITERI,TASIMA_KRITERI) values ('124','Süt-kahvaltýlýk','Buzdolabýnda, -10 derecede','Koli');
Insert into SYSTEM.URUN_GRUPLARI (GRUP_NO,URUN_GRUP_ISIM,SAKLAMA_KRITERI,TASIMA_KRITERI) values ('304','Þekerleme-kuruyemiþ','Rafta, oda sýcaklýðýnda','Koli');
Insert into SYSTEM.URUN_GRUPLARI (GRUP_NO,URUN_GRUP_ISIM,SAKLAMA_KRITERI,TASIMA_KRITERI) values ('36','Et-tavuk-þarküteri','Buzlukta, -15 derecede','Ticari buzluk');
Insert into SYSTEM.URUN_GRUPLARI (GRUP_NO,URUN_GRUP_ISIM,SAKLAMA_KRITERI,TASIMA_KRITERI) values ('294','Meyve sebze','Rafta, 5 derecede','Kasa');
Insert into SYSTEM.URUN_GRUPLARI (GRUP_NO,URUN_GRUP_ISIM,SAKLAMA_KRITERI,TASIMA_KRITERI) values ('438','Unlu mamülleri','Kapalý þeffaf kutuda, kuru ve serin yerde','Kutu');
Insert into SYSTEM.URUN_GRUPLARI (GRUP_NO,URUN_GRUP_ISIM,SAKLAMA_KRITERI,TASIMA_KRITERI) values ('582','Ýçecek','Buzdolabýnda, -3 derecede','Koli');
Insert into SYSTEM.URUN_GRUPLARI (GRUP_NO,URUN_GRUP_ISIM,SAKLAMA_KRITERI,TASIMA_KRITERI) values ('637','Temizlik ','Kuru ve serin yerde','Koli');
Insert into SYSTEM.URUN_GRUPLARI (GRUP_NO,URUN_GRUP_ISIM,SAKLAMA_KRITERI,TASIMA_KRITERI) values ('190','Kiþisel bakým ürünleri','Kuru ve serin yerde','Kutu');
--------------------------------------------------------
--  DDL for Index URUN_GRUPLARI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."URUN_GRUPLARI_PK" ON "SYSTEM"."URUN_GRUPLARI" ("GRUP_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table URUN_GRUPLARI
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."URUN_GRUPLARI" MODIFY ("GRUP_NO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."URUN_GRUPLARI" MODIFY ("URUN_GRUP_ISIM" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."URUN_GRUPLARI" MODIFY ("SAKLAMA_KRITERI" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."URUN_GRUPLARI" MODIFY ("TASIMA_KRITERI" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."URUN_GRUPLARI" ADD CONSTRAINT "URUN_GRUPLARI_PK" PRIMARY KEY ("GRUP_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
